[PACKINGOPT-4] init
vtex-apps/packing-optimization pull request #7
Opened 2022-06-01 13:23 UTC by whc105

2022-06-01 17:26 UTC, btalma approved these changes

2022-06-02 13:44 UTC, polishq requested changes

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +# Packing Optimization
```suggestion
📢 Use this project, [contribute](https://github.com/vtex-apps/packing-optimization) to it or open issues to help evolve it using [Store Discussion](https://github.com/vtex-apps/store-discussion).

# Packing Optimization

<!-- DOCS-IGNORE:start -->
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->

[![All Contributors](https://img.shields.io/badge/all_contributors-0-orange.svg?style=flat-square)](#contributors-)

<!-- ALL-CONTRIBUTORS-BADGE:END -->
<!-- DOCS-IGNORE:end -->
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +## Functionalities 📦
```suggestion

The **Packing Optimization** app provides a REST API that, when provided with a list of available shipping box types and a list of items that need to be packed, will return the most optimal way of packing those items (i.e. fitting the items into the smallest possible number of smallest boxes). By using this app and a diverse set of box sizes, users can experience a significant shipping cost savings.

## Features 📦
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +- Create user defined boxes
```suggestion
- Create and manage a list of available box types
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +- Pack all request body items optimally into the list of user defined boxes
```suggestion
- Pack all provided items optimally into the available box types
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +- In the Admin Panel, `Search` for `Packing Optimization`
```suggestion
- In the VTEX Admin, `Search` for `Packing Optimization`
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +## Configurations ⚙️
```suggestion
## Configuration ⚙️
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +### How to *Access* Configurations
```suggestion
### How to *Access* Configuration
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +- In the `Packing Optimization` app, input your *box length*, *box width*, and *box height*. Box description is optional and press `Add To Table`. The description is for your own purposes and will no
```suggestion
- In the `Packing Optimization` admin panel, input your *box length*, *box width*, and *box height*. Box description is optional and for your own reference. After inputting the desired information, press `Add To Table`. Repeat as desired to register all of your box types.
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +- FedEx App currently integrates with the Packing Optimization App. With the packing app and a diverse set of box sizes, users can experience a significant shipping cost saving.
```suggestion
- [FedEx Shipping](https://github.com/vtex-apps/fedex-shipping)
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +> For performance sake, for situations where we need multiple boxes, we're picking the box with the highest **percentItemVolumePacked**; we pick the largest **percentContainerVolumePacked** as a tieb
```suggestion
> In situations where the app needs multiple boxes, it will pick the box with the highest **percentItemVolumePacked**. In the case of a tie, it picks the box with the largest **percentContainerVolumePacked**.
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +> ⚠️ Currently, the boxes defined have an infinite quantity.
```suggestion
> ⚠️ Currently, the app assumes that there is an infinite available quantity of each box type.
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +> ⚠️ Items that do not fit into any boxes will not be returned. Moreover, there must be at least one box for this app to the utilized.
```suggestion
> ⚠️ Items that do not fit into any boxes will not be returned. Moreover, at least one box type must be defined for this app to be utilized.
```

2022-06-02 13:44 UTC, polishq commented on docs/README.md
> +
```suggestion
## Installation

You can install the **Packing Optimization** app by running `vtex install vtex.packing-optimization` in your terminal, using the [VTEX IO CLI](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-vtex-io-cli-installation-and-command-reference).

```

2022-06-02 14:45 UTC, merged